<?php

/**
 * Implements hook_install().
 */
function gsb_section_autoconfig_install() {
  // Make the weight of our module one higher than workbench_access.
  $weight = db_select('system', 's')
              ->fields('s', array('weight'))
              ->condition('name', 'workbench_access', '=')
              ->execute()
              ->fetchField();

  db_update('system')
    ->fields(array('weight' => $weight +1))
    ->condition('name', 'gsb_section_autoconfig', '=')
    ->execute();
}
